// Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
//
// SPDX-License-Identifier: MIT OR Apache-2.0

use std::fmt;
use std::fs;
use std::io;
use std::path::Path;

use miette::{Report, Result};
use regex::Regex;

mod run;

fn get_error<T: fmt::Debug>(r: Result<T>) -> String {
    let err = r.expect_err("Expected an error");
    error_to_str(err)
}

pub(crate) fn error_to_str(err: Report) -> String {
    let mut res = String::new();
    miette::GraphicalReportHandler::new_themed(miette::GraphicalTheme::unicode_nocolor())
        .with_width(80)
        .render_report(&mut res, err.as_ref())
        .unwrap_or_else(|e| panic!("Failed to render error ({res}): {e}"));
    res
}

/// Split the tests from a tree-sitter style test file and run each of them.
///
/// `file` is the test file from the repo, containing input and expected output for each test.
/// The results generated by `test` are written to `expected_file`, for easy comparison and updates.
///
/// The `test` function gets the input of a test file and generates the output.
/// The output is then compared to the expected output in the test file.
/// panics or returns an error on test failures.
pub(crate) fn run_test_file(
    file: &Path, expected_file: &Path, test: &mut dyn Fn(&str) -> String,
) -> io::Result<()> {
    let name_sep = Regex::new("(?m)^=+$").unwrap();
    let result_sep = Regex::new("(?m)^-+$").unwrap();

    let mut content = fs::read_to_string(file)?;
    // Remove '\r' to achieve test parity between windows and linux
    content = content.replace('\r', "");
    let content = &mut content.as_str();
    let mut expected = String::new();
    let mut test_count = 0;
    let mut failed_tests = Vec::new();

    // For each test
    while let Some(start) = name_sep.find(content) {
        if !expected.is_empty() {
            expected.push('\n');
        }
        expected.push_str(&content[..start.end()]);
        expected.push('\n');
        *content = &content[start.end()..];
        let Some(name_end) = name_sep.find(content) else {
            panic!("Undelimited test {content:?}");
        };

        let name = content[..name_end.start()].trim();
        expected.push_str(name);
        expected.push('\n');
        expected.push_str(&content[name_end.range()]);
        expected.push_str("\n\n");
        *content = &content[name_end.end()..];
        let Some(input_end) = result_sep.find(content) else {
            panic!("Undelimited test input {content:?}");
        };

        let input = content[..input_end.start()].trim();
        expected.push_str(input);
        expected.push_str("\n\n");
        expected.push_str(&content[input_end.range()]);
        expected.push_str("\n\n");
        *content = &content[input_end.end()..];
        let output_end = name_sep.find(content).map_or(content.len()..content.len(), |e| e.range());
        let output = content[..output_end.start].trim();
        *content = &content[output_end.start..];

        // Run test and compare result
        let expected_output = test(input);
        let expected_output = expected_output.trim();
        expected.push_str(expected_output);
        expected.push('\n');
        if output == expected_output {
            println!("{name} passed");
        } else {
            println!("{name} failed");
            println!("Got      {output:?}\nexpected {expected_output:?}");
            failed_tests.push(name);
        }
        test_count += 1;
    }

    fs::write(expected_file, expected.as_bytes())?;
    println!("\nUpdated tests written to {}", expected_file.display());
    println!("Update with cp {} {}", expected_file.display(), file.display());

    if !failed_tests.is_empty() {
        println!("\nFailed tests:\n{}", failed_tests.join("\n"));

        panic!("{}/{test_count} tests failed", failed_tests.len());
    }

    if test_count == 0 {
        panic!("Internal test error. Not running any tests?");
    }

    Ok(())
}
